const LetrinAudioCatalog = {
  'es-AR': {label:'Español de Argentina', clips:{
    A: 'assets/audio/es-AR/letra-a.mp3',
    B: 'assets/audio/es-AR/letra-b.mp3',
    C: 'assets/audio/es-AR/letra-c.mp3',
    D: 'assets/audio/es-AR/letra-d.mp3',
    Helado: 'assets/audio/es-AR/helado.mp3',
    Hilo: 'assets/audio/es-AR/hilo.mp3',
    Huevo: 'assets/audio/es-AR/huevo.mp3',
    Hoja: 'assets/audio/es-AR/hoja.mp3',
    I: 'assets/audio/es-AR/letra-i.mp3',
    Iguana: 'assets/audio/es-AR/iguana.mp3',
    'Iglú': 'assets/audio/es-AR/iglu.mp3',
    Isla: 'assets/audio/es-AR/isla.mp3',
    'Imán': 'assets/audio/es-AR/iman.mp3',
    G: 'assets/audio/es-AR/letra-g.mp3',
    Gato: 'assets/audio/es-AR/gato.mp3',
    Gota: 'assets/audio/es-AR/gota.mp3',
    Gallina: 'assets/audio/es-AR/gallina.mp3',
    Gorila: 'assets/audio/es-AR/gorila.mp3',
    F: 'assets/audio/es-AR/letra-f.mp3',
    Flor: 'assets/audio/es-AR/flor.mp3',
    Fuego: 'assets/audio/es-AR/fuego.mp3',
    Fantasma: 'assets/audio/es-AR/fantasma.mp3',
    Frutilla: 'assets/audio/es-AR/frutilla.mp3',
    E: 'assets/audio/es-AR/letra-e.mp3',
    Elefante: 'assets/audio/es-AR/elefante.mp3',
    Estrella: 'assets/audio/es-AR/estrella.mp3',
    Escoba: 'assets/audio/es-AR/escoba.mp3',
    Espejo: 'assets/audio/es-AR/espejo.mp3',
    Dado: 'assets/audio/es-AR/dado.mp3',
    'Delfín': 'assets/audio/es-AR/delfin.mp3',
    Diente: 'assets/audio/es-AR/diente.mp3',
    Durazno: 'assets/audio/es-AR/durazno.mp3',
    Casa: 'assets/audio/es-AR/casa.mp3',
    Cama: 'assets/audio/es-AR/cama.mp3',
    Conejo: 'assets/audio/es-AR/conejo.mp3',
    'Corazón': 'assets/audio/es-AR/corazon.mp3',
    Barco: 'assets/audio/es-AR/barco.mp3',
    Banana: 'assets/audio/es-AR/banana.mp3',
    Ballena: 'assets/audio/es-AR/ballena.mp3',
    Bicicleta: 'assets/audio/es-AR/bicicleta.mp3',
    Abeja: 'assets/audio/es-AR/abeja.mp3',
    'Avión': 'assets/audio/es-AR/avion.mp3',
    'Árbol': 'assets/audio/es-AR/arbol.mp3',
    'Araña': 'assets/audio/es-AR/arana.mp3'
  }},
  'es-419': {label:'Español de Latinoamérica', clips:{}},
  'es-MX': {label:'Español de México', clips:{}},
  'es-ES': {label:'Español de España', clips:{}}
};
