
const CACHE = 'letrin-v0-80';
const LANGUAGE_ASSETS = ['language.js?v=80','letters-en.js?v=80','assets/en-ant.webp','assets/en-anchor.webp','assets/en-car.webp','assets/en-cake.webp','assets/en-door.webp','assets/en-elbow.webp','assets/en-envelope.webp',...['letter-a','apple','ant','airplane','anchor','letter-b','ball','bear','boat','banana','letter-c','cat','car','cow','cake','letter-d','dog','duck','dolphin','door','letter-e','elephant','egg','elbow','envelope'].map(word=>`assets/audio/en-US/${word}.mp3`)];
const ASSETS = ['./', 'index.html', 'styles.css', 'app.js', 'manifest.json', 'assets/milo.webp', 'assets/garden.svg', 'assets/milo-peeking.webp', 'assets/milo-celebrando.webp', 'assets/abeja.webp', 'assets/avion.webp', 'assets/arbol.webp', 'assets/arana.webp'];
self.addEventListener('install', event => {
  ASSETS.push('soundtrack.js?v=80','soundtrack.js','audio.js?v=80','styles.css?v=80','assets/audio/patterns-of-play.mp3');
  ASSETS.push(...['letra-z','zapato','zorro','zanahoria','zapallo'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['zapato','zorro','zanahoria','zapallo','letra-z-roja','letra-z-verde','actividad-trazar-z','actividad-atrapar-z'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["yacare","yate","yoyo","yogur","letra-y-roja","letra-y-verde","actividad-trazar-y","actividad-atrapar-y"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["letra-y","yacare","yate","yoyo","yogur"].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-x','xilofono','taxi','excavadora','saxofon'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...["xilofono","taxi","excavadora","saxofon","letra-x-roja","letra-x-verde","actividad-trazar-x","actividad-atrapar-x"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-w','waffle','wok','kiwi','sandwich'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...["waffle","wok","sandwich","letra-w-roja","letra-w-verde","actividad-trazar-w","actividad-atrapar-w","kiwi"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-v','vaca','vaso','vela','violin'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...["vaca","vaso","vela","violin","letra-v-roja","letra-v-verde","actividad-trazar-v","actividad-atrapar-v"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-u','uva','unicornio','uno','unia'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...["uva","unicornio","uno","unia","letra-u-roja","letra-u-verde","actividad-trazar-u","actividad-atrapar-u"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-t','tortuga','tren','tomate','tigre'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-j','jirafa','jabon','jugo','jaula'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['jirafa','jabon','jugo','jaula','letra-j-roja','letra-j-verde','actividad-trazar-j','actividad-atrapar-j'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-i','iguana','iglu','isla','iman'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['iguana','iglu','isla','iman','letra-i-roja','letra-i-verde','actividad-trazar-i','actividad-atrapar-i'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['helado','hilo','huevo','hoja'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['helado','hoja','huevo','hilo','letra-h-roja','letra-h-verde','actividad-trazar-h','actividad-atrapar-h'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-g','gato','gota','gallina','gorila'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['gato','gorila','gallina','gota','letra-g-roja','letra-g-verde','actividad-trazar-g','actividad-atrapar-g'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-f','flor','fuego','fantasma','frutilla'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['fuego','flor','frutilla','fantasma','letra-f-roja','letra-f-verde','actividad-trazar-f','actividad-atrapar-f'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-e','elefante','estrella','escoba','espejo'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['elefante','estrella','escoba','espejo','letra-e-roja','letra-e-verde','actividad-trazar-e','actividad-atrapar-e'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['dado','delfin','diente','durazno','letra-d-roja','letra-d-verde','actividad-trazar-d','actividad-atrapar-d'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...['letra-d','dado','delfin','diente','durazno'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push('assets/koala.webp','assets/kiwi.webp','assets/kiosco.webp','assets/kayak.webp','assets/letra-k-roja.webp','assets/letra-k-verde.webp','assets/actividad-trazar-k.webp','assets/actividad-atrapar-k.webp');
  ASSETS.push('assets/leon.webp','assets/luna.webp','assets/lapiz.webp','assets/limon.webp','assets/letra-l-roja.webp','assets/letra-l-verde.webp','assets/actividad-trazar-l.webp','assets/actividad-atrapar-l.webp');
  ASSETS.push('assets/mariposa.webp','assets/manzana.webp','assets/mono.webp','assets/moto.webp','assets/letra-m-roja.webp','assets/letra-m-verde.webp','assets/actividad-trazar-m.webp','assets/actividad-atrapar-m.webp');
  ASSETS.push('assets/naranja.webp','assets/nube.webp','assets/nido.webp','assets/nutria.webp','assets/letra-n-roja.webp','assets/letra-n-verde.webp','assets/actividad-trazar-n.webp','assets/actividad-atrapar-n.webp');
  ASSETS.push('assets/nandu.webp','assets/noquis.webp','assets/mono-lazo.webp','assets/pinata.webp','assets/letra-enie-roja.webp','assets/letra-enie-verde.webp','assets/actividad-trazar-enie.webp','assets/actividad-atrapar-enie.webp');
  ASSETS.push(...["oso","oveja","oruga","oreja","letra-o-roja","letra-o-verde","actividad-trazar-o","actividad-atrapar-o"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["pelota","pato","pez","pera","letra-p-roja","letra-p-verde","actividad-trazar-p","actividad-atrapar-p"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["queso","quena","mosquito","raqueta","letra-q-roja","letra-q-verde","actividad-trazar-q","actividad-atrapar-q"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["rana","raton","reloj","rosa","letra-r-roja","letra-r-verde","actividad-trazar-r","actividad-atrapar-r"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["sol","sapo","sandia","sombrero","letra-s-roja","letra-s-verde","actividad-trazar-s","actividad-atrapar-s"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push(...["tortuga","tren","tomate","tigre","letra-t-roja","letra-t-verde","actividad-trazar-t","actividad-atrapar-t"].map(asset=>`assets/${asset}.webp`));
  ASSETS.push('styles.css?v=49','app.js?v=80','letters.js?v=80','letter-path.js?v=80');
  ASSETS.push(...['cama','conejo','corazon','letra-c-roja','letra-c-verde','actividad-trazar-c','actividad-atrapar-c'].map(asset=>`assets/${asset}.webp`));
  ASSETS.push('assets/actividad-trazar-b.webp','assets/actividad-atrapar-b.webp');
  ASSETS.push('assets/ballena.webp','assets/bicicleta.webp','assets/letra-b-roja.webp','assets/letra-b-verde.webp');
  ASSETS.push('assets/app-icon-192.png','assets/app-icon-512.png','assets/app-icon-maskable-512.png');
  ASSETS.push(...['abeja','avion','arbol','arana'].map(word => `assets/audio/es-AR/${word}.mp3`));
  ASSETS.push('assets/audio/es-AR/letra-a.mp3');
  ASSETS.push(...['letra-b','barco','banana','ballena','bicicleta'].map(word => `assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-c','casa','cama','conejo','corazon'].map(word => `assets/audio/es-AR/${word}.mp3`));
  ASSETS.push('styles.css?v=30','app.js?v=30','letter-path.js?v=30');
  ASSETS.push('styles.css?v=29','app.js?v=29');
  ASSETS.push('styles.css?v=28','app.js?v=28','letter-path.js?v=28','assets/milo-pintar.webp','assets/milo-trazar.webp');
  ASSETS.push(...['letra-k','koala','kiwi','kiosco','kayak'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-l','leon','luna','lapiz','limon'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-m','mariposa','manzana','mono','moto'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-n','naranja','nube','nido','nutria'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-s','sol','sapo','sandia','sombrero'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-r','rana','raton','reloj','rosa'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-q','queso','quena','mosquito','raqueta'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-p','pelota','pato','pez','pera'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-o','oso','oveja','oruga','oreja'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push(...['letra-enie','nandu','noquis','mono-lazo','pinata'].map(word=>`assets/audio/es-AR/${word}.mp3`));
  ASSETS.push('audio.js?v=39','audio-catalog.js?v=80');
  ASSETS.push('styles.css?v=25','app.js?v=25','letter-path.js?v=25','audio.js','audio-catalog.js','audio.js?v=25','audio-catalog.js?v=25','assets/ui-icons.svg','assets/letra-a-roja.webp','assets/letra-a-verde.webp');
  ASSETS.push(...['trazar','pintar','elegir','atrapar'].map(asset => `assets/actividad-${asset}.webp`));
  ASSETS.push(...['sol','oso','casa','pelota','luna','barco','flor','gato','banana'].map(asset => `assets/${asset}.webp`));
  ASSETS.push('letter-path.js','assets/fonts/nunito.ttf','assets/milo-fiesta-0.webp','assets/milo-fiesta-1.webp','assets/milo-fiesta-2.webp','assets/milo-fiesta-3.webp','assets/milo-fiesta-4.webp');
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll([...new Set([...ASSETS,...LANGUAGE_ASSETS])])).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('letrin-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(fetch(event.request, {cache:'no-cache'}).then(response => {
    if (response.ok) {
      const copy = response.clone();
      event.waitUntil(caches.open(CACHE).then(cache => cache.put(event.request, copy)));
    }
    return response;
  }).catch(async () => {
    const cached = await caches.match(event.request);
    if (cached) return cached;
    if (event.request.mode === 'navigate') return caches.match('index.html');
    return Response.error();
  }));
});
